# frozen_string_literal: true
require 'fastly/version'

require 'logger'
require 'securerandom'

require 'cistern'

module Fastly
  include Cistern::Client.with(interface: :module)

  USER_AGENT = "Fastly/#{Fastly::VERSION} Ruby/#{RUBY_VERSION} (#{RUBY_PLATFORM}; #{RUBY_ENGINE}"

  recognizes :username, :password, :token, :url, :adapter, :logger
end

require 'fastly/response'
require 'fastly/request'
require 'fastly/collection'
require 'fastly/service_version_model'

require 'fastly/customer'
require 'fastly/customers'
require 'fastly/get_customer'
require 'fastly/get_current_customer'

require 'fastly/get_service'
require 'fastly/get_services'
require 'fastly/create_service'
require 'fastly/destroy_service'
require 'fastly/update_service'
require 'fastly/search_services'
require 'fastly/service'
require 'fastly/services'

require 'fastly/create_version'
require 'fastly/get_versions'
require 'fastly/get_version'
require 'fastly/update_version'
require 'fastly/activate_version'
require 'fastly/deactivate_version'
require 'fastly/clone_version'
require 'fastly/validate_version'
require 'fastly/lock_version'
require 'fastly/version_model'
require 'fastly/versions'

require 'fastly/backend'
require 'fastly/backends'
require 'fastly/create_backend'
require 'fastly/get_backends'
require 'fastly/get_backend'
require 'fastly/update_backend'
require 'fastly/destroy_backend'

require 'fastly/domain'
require 'fastly/domains'
require 'fastly/create_domain'
require 'fastly/get_domains'
require 'fastly/get_domain'
require 'fastly/update_domain'
require 'fastly/destroy_domain'

require 'fastly/dictionary'
require 'fastly/dictionaries'
require 'fastly/create_dictionary'
require 'fastly/get_dictionaries'
require 'fastly/get_dictionary'
require 'fastly/update_dictionary'
require 'fastly/destroy_dictionary'

require 'fastly/dictionary_item'
require 'fastly/dictionary_items'
require 'fastly/create_dictionary_item'
require 'fastly/get_dictionary_items'
require 'fastly/get_dictionary_item'
require 'fastly/upsert_dictionary_item'
require 'fastly/destroy_dictionary_item'

require 'fastly/condition'
require 'fastly/conditions'
require 'fastly/create_condition'
require 'fastly/get_condition'
require 'fastly/get_conditions'
require 'fastly/update_condition'
require 'fastly/destroy_condition'

require 'fastly/director'
require 'fastly/directors'
require 'fastly/create_director'
require 'fastly/get_director'
require 'fastly/get_directors'
require 'fastly/update_director'
require 'fastly/destroy_director'

require 'fastly/header'
require 'fastly/headers'
require 'fastly/create_header'
require 'fastly/get_header'
require 'fastly/get_headers'
require 'fastly/update_header'
require 'fastly/destroy_header'

require 'fastly/healthcheck'
require 'fastly/healthchecks'
require 'fastly/healthcheck_request'
require 'fastly/create_healthcheck'
require 'fastly/get_healthcheck'
require 'fastly/get_healthchecks'
require 'fastly/update_healthcheck'
require 'fastly/destroy_healthcheck'

require 'fastly/request_setting'
require 'fastly/request_settings'
require 'fastly/create_request_setting'
require 'fastly/get_request_setting'
require 'fastly/get_request_settings'
require 'fastly/update_request_setting'
require 'fastly/destroy_request_setting'

require 'fastly/settings'
require 'fastly/get_settings'
require 'fastly/update_settings'

require 'fastly/acl'
require 'fastly/acls'
require 'fastly/create_acl'
require 'fastly/get_acls'
require 'fastly/get_acl'
require 'fastly/update_acl'
require 'fastly/destroy_acl'

require 'fastly/acl_entry'
require 'fastly/acl_entries'
require 'fastly/create_acl_entry'
require 'fastly/get_acl_entries'
require 'fastly/get_acl_entry'
require 'fastly/update_acl_entry'
require 'fastly/destroy_acl_entry'

require 'fastly/gzip'
require 'fastly/gzips'
require 'fastly/create_gzip'
require 'fastly/get_gzip'
require 'fastly/get_gzips'
require 'fastly/update_gzip'
require 'fastly/destroy_gzip'

require 'fastly/logger'
require 'fastly/loggers'
require 'fastly/create_logger'
require 'fastly/get_logger'
require 'fastly/get_loggers'
require 'fastly/update_logger'
require 'fastly/destroy_logger'

require 'fastly/diff'
require 'fastly/get_version_diff'

require 'fastly/response_object'
require 'fastly/response_objects'
require 'fastly/create_response_object'
require 'fastly/get_response_object'
require 'fastly/get_response_objects'

require 'fastly/real'
require 'fastly/mock'
